# Generated by Django 4.2.30 on 2026-06-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
    ]
