# Generated by Django 6.0.3 on 2026-04-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField(verbose_name='Début de période')),
                ('periode_fin', models.DateField(verbose_name='Fin de période')),
                ('heures_travaillees', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Heures travaillées')),
                ('heures_supplementaires', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Heures supplémentaires')),
                ('nb_absences', models.IntegerField(default=0, verbose_name="Nombre d'absences")),
                ('nb_retards', models.IntegerField(default=0, verbose_name='Nombre de retards')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire de base')),
                ('prime_heures_sup', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prime heures sup.')),
                ('deduction_absences', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Déduction absences')),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire brut')),
                ('cnss', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='CNSS')),
                ('impot', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Impôt sur le revenu')),
                ('autres_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Autres déductions')),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire net')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
            ],
            options={
                'verbose_name': 'Bulletin de salaire',
                'verbose_name_plural': 'Bulletins de salaire',
                'ordering': ['-periode_debut'],
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé Annuel'), ('maladie', 'Congé Maladie'), ('maternite', 'Congé Maternité'), ('paternite', 'Congé Paternité'), ('sans_solde', 'Congé Sans Solde'), ('exceptionnel', 'Congé Exceptionnel'), ('formation', 'Congé Formation')], max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('duree_jours', models.IntegerField(help_text='Durée en jours ouvrés')),
                ('statut', models.CharField(choices=[('en_attente', 'En Attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField(help_text='Motif de la demande de congé')),
                ('commentaire_rh', models.TextField(blank=True, help_text='Commentaire du RH/Admin')),
                ('document_attache', models.FileField(blank=True, null=True, upload_to='documents_conges/')),
                ('solde_avant', models.DecimalField(decimal_places=1, default=0.0, help_text='Solde de congés avant cette demande', max_digits=4)),
                ('solde_apres', models.DecimalField(decimal_places=1, default=0.0, help_text='Solde de congés après cette demande', max_digits=4)),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_permission', models.CharField(choices=[('leave', 'Congé'), ('absence', 'Absence'), ('sick_leave', 'Arrêt maladie'), ('maternity', 'Congé maternité'), ('paternity', 'Congé paternité'), ('unpaid', 'Congé sans solde')], max_length=20)),
                ('date_sortie', models.DateTimeField(verbose_name='Date de sortie')),
                ('date_retour', models.DateTimeField(verbose_name='Date de retour')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('commentaire_rh', models.TextField(blank=True, verbose_name='Commentaire RH')),
            ],
            options={
                'verbose_name': 'Demande de permission',
                'verbose_name_plural': 'Demandes de permission',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_rapport', models.CharField(choices=[('presence', 'Rapport de Présence'), ('activite', "Rapport d'Activité"), ('performance', 'Rapport de Performance'), ('conges', 'Rapport de Congés'), ('bulletins', 'Rapport de Bulletins'), ('violations', 'Rapport de Violations'), ('statistiques', 'Rapport Statistiques')], max_length=20)),
                ('periode_rapport', models.CharField(choices=[('jour', 'Journalier'), ('semaine', 'Hebdomadaire'), ('mois', 'Mensuel'), ('trimestre', 'Trimestriel'), ('semestre', 'Semestriel'), ('annee', 'Annuel'), ('personnalise', 'Personnalisé')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('contenu', models.TextField(help_text='Contenu détaillé du rapport')),
                ('fichier_attache', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En Cours'), ('termine', 'Terminé'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20)),
                ('filtres', models.JSONField(blank=True, default=dict, help_text='Filtres appliqués au rapport')),
                ('parametres', models.JSONField(blank=True, default=dict, help_text='Paramètres de génération')),
                ('total_enregistrements', models.IntegerField(default=0, help_text="Nombre total d'enregistrements")),
                ('total_heures', models.DecimalField(decimal_places=2, default=0.0, help_text='Total des heures', max_digits=8)),
                ('pourcentage_presence', models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage de présence', max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='Solde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_annuel', models.DecimalField(decimal_places=1, default=25.0, help_text='Solde annuel de congés en jours', max_digits=4)),
                ('conges_pris', models.DecimalField(decimal_places=1, default=0.0, help_text='Nombre de jours de congés pris', max_digits=4)),
                ('conges_restant', models.DecimalField(decimal_places=1, default=25.0, help_text='Solde de congés restant', max_digits=4)),
                ('annee_reference', models.IntegerField(default=2026, help_text='Année de référence des soldes')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solde de Congés',
                'verbose_name_plural': 'Soldes de Congés',
                'ordering': ['-annee_reference', 'employe__username'],
            },
        ),
    ]
