# Generated by Django 6.0.3 on 2026-04-03 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='genere_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_generees', to=settings.AUTH_USER_MODEL, verbose_name='Généré par'),
        ),
        migrations.AddField(
            model_name='conge',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conge',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='rh_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_traitees', to=settings.AUTH_USER_MODEL, verbose_name='RH traitant'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapport',
            name='destinataires',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs ayant accès au rapport', related_name='rapports_recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapport',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solde',
            name='employe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde_conges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solde',
            name='mis_a_jour_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soldes_mis_a_jour', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bulletin',
            unique_together={('employee', 'periode_debut', 'periode_fin')},
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['type_rapport', 'date_debut'], name='core_rappor_type_ra_a24f38_idx'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['auteur', 'statut'], name='core_rappor_auteur__95d81d_idx'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['date_generation'], name='core_rappor_date_ge_162c13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='solde',
            unique_together={('employe', 'annee_reference')},
        ),
    ]
