# Generated by Django 4.2.30 on 2026-04-30 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('debut_pause', models.TimeField(blank=True, null=True, verbose_name='Début pause')),
                ('fin_pause', models.TimeField(blank=True, null=True, verbose_name='Fin pause')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('retard', 'Retard'), ('absent', 'Absent'), ('permission', 'Permission'), ('conge', 'Congé')], default='absent', max_length=20, verbose_name='Statut')),
                ('minutes_retard', models.IntegerField(default=0, verbose_name='Minutes de retard')),
                ('heures_travaillees', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Heures travaillées')),
                ('pause_respectee', models.BooleanField(default=False, verbose_name='Pause respectée')),
                ('minutes_retard_pause', models.IntegerField(default=0, verbose_name='Minutes de retard sur pause')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-date', '-heure_arrivee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
