# Generated by Django 4.2 on 2026-05-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_permissionrequest_status_pointage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='pause_respectee',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pause respectée'),
        ),
    ]
