# Generated by Django 4.2.30 on 2026-06-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pointage_pause_respectee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='type_permission',
            field=models.CharField(choices=[('permission', 'Permission'), ('leave', 'Congé'), ('absence', 'Absence'), ('sick_leave', 'Arrêt maladie'), ('maternity', 'Congé maternité'), ('paternity', 'Congé paternité'), ('unpaid', 'Congé sans solde')], max_length=20),
        ),
    ]
